### ISSUE TITLE
Minimal version of this - Numeric Types Only 

### ISSUE THREAD

**Issue by c69** [littledan/proposal-operator-overloading#11]
Javascript is untyped language, and i'm not sure if its even possible to have a performant implementation of operator overloading without either (or both) Types and Compilation.

Still, the current version of proposal contains a very promising hack `_px` and so on - which is basically "unit of measure" or custom numeric types.

If it is possible to allow

```
import { px, em } from 'css-typed-om/units';

let a = 2_px + 2_px
```

but its hard to extend such approach to non-scalar values:

```
import { matrix as m, Matrix, vector as v } from 'super-math/units-with-operators';

let a = 5 * (new Matrix([[1,2,3],[5,6,7,]]))_m; // not really looking good..

let M = new Matrix([[1,2,3],[4,5,6]]);
let b = 5 * (M)_m; // still ugly, but not as much 
```

p.s.: this means only the Field operators (+, *, -, /) and comparison (<, >, >=, <=, ==) can be overloaded. Their behavior is supposed to be based on conventional math. [ ] is out of scope, and bit shifts too. Operator overloading for Arrays, Sets and all the nicer (more complicated stuff is also out of scope).

p.p.s: *this is just a strawman*, seeing how none of the operator overloading proposal in JS ever made it anywhere - maybe some small solution solving some very practical issue (say: math, css, ai/ml) can be a first stepping stone.

**Comment by littledan** [comment]
It's unclear to me what semantics you are proposing. How would numeric types be distinguished, if they are in a variable?

**Comment by c69** [comment]
I propose a special punctuation to mark numeric types during arithmetic operations.

It's `_` to be similar with original proposal, but the actual character does not matter #noBikeshedding

```
import {
  numberPostfix as nx,
  optionalNumberConstructor as Cx
} from 'number-library'; // where + is overloaded

let a = new Cx(...params); // a is instance of Cx, without value semantics
let a2 = a + a; // behaves just as current ES, just coerses to "nearest" js type (either number or string) via .toString() or .valueOf()

let b = new Cx(..params)_nx; // b is still an instance of Cx, without value semantics
let b20 = b + b; // same as before
let b21 = (b) + (b); // same as before

let b22 = (b)_nx + (b)_nx; // overloaded "+" actually triggers, b2 is now a "sum" of b and b

```
p.s.: hopefully, the code example makes it a bit more clear.

**Comment by littledan** [comment]
Well, after the code is executed, how is that punctuation mark held in the value?

**Comment by c69** [comment]
in this strawman this is not possible. 

I think if anyone can resolve "how to hold both value and type (without ruining performance)", then my strawman is not needed, because then you can just use operators without extra syntax.

**Comment by littledan** [comment]
I don't see how this would fit cleanly into the JavaScript language, where functions and operators treat their parameters as expressions, rather than looking into their internal syntax. I agree that we should not hurt JS performance, and that we should not add operator overloading to JS if it will make it slower.
