### ISSUE TITLE
What about mention AssemblyScript in "Cross-language comparison"?

### ISSUE THREAD

**Issue by MaxGraey** [littledan/proposal-operator-overloading#9]
[AssemblyScript](https://github.com/AssemblyScript/assemblyscript) already implement similar abilities along time ago. See [examples](https://github.com/AssemblyScript/assemblyscript/blob/master/tests/compiler/std/operator-overloading.ts)

**Comment by littledan** [comment]
Thanks for the reference, I didn't know about this. PRs welcome for adding the reference.
